=== MuntashirAkon/android-debloat-list/schema/bloatware_list.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://muntashirakon.github.io/android-debloat-list/bloatware_list.json",
    "title": "Bloatware List",
    "description": "Listing of Android bloatware",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "description": "Bloatware package name",
                "type": "string"
            },
            "label": {
                "description": "Bloatware package label",
                "type": "string"
            },
            "dependencies": {
                "description": "Packages that this bloatware depends on",
                "type": "array",
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "uniqueItems": true
            },
            "required_by": {
                "description": "Packages that depend on this bloatware",
                "type": "array",
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "uniqueItems": true
            },
            "tags": {
                "description": "Predefined tags",
                "type": "array",
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "uniqueItems": true
            },
            "description": {
                "description": "Bloatware description",
                "type": "string"
            },
            "web": {
                "description": "Online references",
                "type": "array",
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "uniqueItems": true
            },
            "removal": {
                "description": "Bloatware removal type (delete, replace, caution, unsafe)",
                "type": "string",
                "enum": [
                    "delete",
                    "replace",
                    "caution",
                    "unsafe"
                ]
            },
            "warning": {
                "description": "Possible consequences of removing the bloatware (for caution and unsafe), for others, useful information",
                "type": "string"
            },
            "suggestions": {
                "description": "Suggestion ID for listing alternatives to this bloatware",
                "type": "string"
            }
        },
        "required": [
            "id",
            "label",
            "description",
            "removal"
        ]
    },
    "uniqueItems": true
}

=== MuntashirAkon/android-debloat-list/carrier.json
[
    {
        "id": "com.aura.oobe.vodafone",
        "label": "Vodafone AppBox",
        "description": "It is some kind of post-install recommended apps setup from the carrier.\nAsks for your age and gender and then recommends you to install popular apps.\nDevelopped by IronSource, an Israeli advertising company.",
        "removal": "delete"
    },
    {
        "id": "com.ironsource.appcloud.oobe.hutchison",
        "label": "AppCloud",
        "description": "AppCloud (discontinued) from ironSource, an advertising company.\nWorth reading:",
        "web": [
            "https://en.wikipedia.org/wiki/IronSource"
        ],
        "removal": "delete"
    },
    {
        "id": "com.dti.bouyguestelecom",
        "label": "Bouygues AppCloud",
        "description": "Its problably for install apps but its useless and have ads and a lot permissions.",
        "removal": "delete"
    },
    {
        "id": "com.altice.android.myapps",
        "label": "MyApps",
        "description": "Its problably for install apps but its useless.",
        "removal": "delete"
    },
    {
        "id": "com.sfr.android.sfrjeux",
        "label": "My Games",
        "description": "Its not useful app for games and better uninstall it",
        "removal": "delete"
    },
    {
        "id": "com.felicanetworks.mfc",
        "label": "com.felicanetworks.mfc",
        "description": "Chinese felicanetworks",
        "removal": "delete"
    },
    {
        "id": "com.felicanetworks.mfm.main",
        "label": "com.felicanetworks.mfm.main",
        "description": "Chinese felicanetworks",
        "removal": "delete"
    },
    {
        "id": "com.felicanetworks.mfs",
        "label": "com.felicanetworks.mfs",
        "description": "Chinese felicanetworks",
        "removal": "delete"
    },
    {
        "id": "com.felicanetworks.mfw.a.boot",
        "label": "com.felicanetworks.mfw.a.boot",
        "description": "Chinese felicanetworks",
        "removal": "delete"
    },
    {
        "id": "com.aura.oobe.motorola",
        "label": "MotoApps",
        "description": "It's something to install apps, but it's an advertising company.",
        "removal": "delete"
    },
    {
        "id": "com.dti.motorola",
        "label": "Mobile Services Manager",
        "description": "Its something for install apps but its useless and a lot permissions.",
        "removal": "delete"
    },
    {
        "id": "com.claroColombia.contenedor",
        "label": "Claro",
        "description": "It's something to install apps, but it's an advertising company.",
        "removal": "delete"
    },
    {
        "id": "com.dti.cricket",
        "label": "com.dti.cricket",
        "description": "Its app for installing recommanded apps? Its only used on first-boot setup and its useless.",
        "removal": "delete"
    },
    {
        "id": "com.cricketwireless.minus",
        "label": "com.cricketwireless.minus",
        "description": "Cricket partner tab? better remove it. It problably have news or partner customization to chrome.",
        "removal": "delete"
    },
    {
        "id": "com.att.deviceunlock",
        "label": "Device Unlock",
        "description": "Useless app from AT&T. Its only for unlock device.",
        "removal": "delete"
    },
    {
        "id": "com.oem.euiccpartnerapp",
        "label": "EuiccPartnerApp",
        "description": "Needed for eSIM (eUICC)?\nI think its useless.",
        "removal": "delete"
    },
    {
        "id": "com.oem.euiccpartnerapp",
        "label": "EuiccPartnerApp",
        "description": "Needed for eSIM (eUICC)?\nI think its useless.",
        "removal": "delete"
    },
    {
        "id": "com.inmobi.installer",
        "label": "com.inmobi.installer",
        "description": "Its installer advertising company app.",
        "removal": "delete"
    },
    {
        "id": "com.verizon.services",
        "label": "AppDirectedSMS",
        "description": "OMA Device Management for Verizon.\nIts for wifi calling, sms",
        "removal": "replace"
    },
    {
        "id": "com.dti.amx",
        "label": "com.dti.amx",
        "description": "Its used to choose app install? A lot trackers, permissions.\nUseless.",
        "removal": "delete"
    },
    {
        "id": "ca.bell.wt.android.tunesappswidget",
        "label": "App Widget",
        "description": "Developped by Bell Canada, it is a home screen widget which shows advertisements, promotions, news, sports & entertainment.",
        "web": [
            "https://play.google.com/store/apps/details?id=ca.bell.wt.android.tunesappswidget"
        ],
        "removal": "delete"
    },
    {
        "id": "com.LogiaGroup.LogiaDeck",
        "label": "Mobile Services Manager",
        "description": "\"Mobile Services Manager/DTIGNITE malware, rooted to your device by express agreement between the app's publisher and your carrier.\"",
        "web": [
            "https://www.reddit.com/r/lgv20/comments/6u0wnf/what_is_mobile_services_manager_did_i_catch_a/"
        ],
        "removal": "delete"
    },
    {
        "id": "com.Rogers.MyRogersTab",
        "description": "Appears to be the tablet version of MyRogers (https://play.google.com/store/apps/details?id=com.fivemobile.myaccount), an app to manage your account with Canadian carrier Rogers.",
        "removal": "delete"
    },
    {
        "id": "com.aetherpal.attdh.se",
        "label": "Device Help",
        "description": "Device Help for AT&T Samsung device.\nDeveloped by Aetherpal, a company which sells smart remote controls tools.\nI guess this app is used for tech support.",
        "web": [
            "https://docs.samsungknox.com/CCMode/G935A_O.pdf",
            "https://en.wikipedia.org/wiki/AetherPal"
        ],
        "removal": "delete"
    },
    {
        "id": "com.aetherpal.attdh.zte",
        "label": "Device Help",
        "description": "Device Help for AT&T ZTE devices.\nDeveloped by Aetherpal, a company which sells smart remote controls tools.\nI guess this app is used for tech support.",
        "web": [
            "https://en.wikipedia.org/wiki/AetherPal"
        ],
        "removal": "delete"
    },
    {
        "id": "com.altice.android.myapps",
        "description": "MyApps\nit's probably for install apps but it's useless.",
        "removal": "delete"
    },
    {
        "id": "com.americanexpress.plenti",
        "description": "Plenti\nGet points and promos with your American Express card",
        "removal": "delete"
    },
    {
        "id": "com.android.partnerbrowsercustomizations.tmobile",
        "description": "The proprietary application of the mobile operator T-Mobile, presumably displays ads, is responsible for the operation of some of the operator's settings",
        "removal": "delete"
    },
    {
        "id": "com.android.sprint.hiddenmenuapp",
        "label": "HiddenMenu",
        "description": "Lets you access hidden features tests/settings (you need to type a special code in the dialer).",
        "web": [
            "https://bestcellular.com/dial-codes/"
        ],
        "removal": "delete"
    },
    {
        "id": "com.android.wifi.resources.overlay.WifiVodafoneOverlay",
        "label": "com.android.wifi.resources.overlay.WifiVodafoneOverlay",
        "description": "Not sure what it does",
        "web": [
            "https://beta.pithus.org/report/d8b19f854eb85ea97fbaeafb8c11842cf9b27f169b08d3e8b2659f52db9dd408"
        ],
        "removal": "delete"
    },
    {
        "id": "com.asurion.android.mobilerecovery.att",
        "label": "AT&T Protect Plus",
        "description": "Discontinued and replaced by AT&T ProTech (com.asurion.android.protech.att)\nHelp and support app. Lets you call or chat with a live U.S.-based AT&T ProTech support expert.",
        "web": [
            "https://en.wikipedia.org/wiki/Asurion"
        ],
        "removal": "delete",
        "warning": "This app is developed by Asurion, a US company whose business is to sell insurances. All US carriers use Asurion for the phone insurances."
    },
    {
        "id": "com.asurion.android.mobilerecovery.sprint",
        "label": "Sprint Protect",
        "description": "Let you find a phone, secure from viruses, back up data, and more.",
        "web": [
            "https://en.wikipedia.org/wiki/Asurion"
        ],
        "removal": "delete",
        "warning": "This app is developed by Asurion, a US company whose business is to sell insurances. All US carriers use Asurion for the phone insurances."
    },
    {
        "id": "com.asurion.android.mobilerecovery.sprint.vpl",
        "label": "Sprint Protect",
        "description": "Let you find a phone, secure from viruses, back up data, and more.",
        "web": [
            "https://en.wikipedia.org/wiki/Asurion"
        ],
        "removal": "delete",
        "warning": "This app is developed by Asurion, a US company whose business is to sell insurances. All US carriers use Asurion for the phone insurances."
    },
    {
        "id": "com.asurion.android.protech.att",
        "label": "AT&T ProTech",
        "description": "Help and support app. Lets you call or chat with a live U.S.-based AT&T ProTech support \"expert\".",
        "web": [
            "https://en.wikipedia.org/wiki/Asurion"
        ],
        "removal": "delete",
        "warning": "This app is developed by Asurion, a US company whose business is to sell insurances. All US carriers use Asurion for the phone insurances."
    },
    {
        "id": "com.asurion.android.verizon.vms",
        "label": "Digital Secure",
        "description": "Verizon's one-stop suite of privacy and security tools that is supposed to protect your devices from online threats, connect to public Wi-Fi with a secure VPN, take control with always-on dark web monitoring, and get guidance on online security from \"security experts\".",
        "web": [
